name: Build Python Package

on:
  workflow_dispatch:
  release:
    types: [created]
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python_version: ['3.7', '3.8', '3.9']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
        pip install cython matplotlib numpy scikit-learn scipy
    - name: Build and publish
      run: |
        python setup.py sdist bdist_wheel
    - uses: softprops/action-gh-release@78c309ef59fdb9557cd6574f2e0be552936ed728
      with:
        draft: true
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
